# name for the action
# action is actually a seperate feature (which will be explored later)
name: First Workflow

# Define when the workflow should be executed
# by specifying the event / events that should trigger the workflow to run.
# workflow_dispatch means that we can manually trigger the workflow
on: workflow_dispatch

# the work to be done
# "jobs" but not "job"
jobs:
  first-job:
    # define the runner on which the job will execute the different steps,
    # so the environment in which the different steps should be executed
    # github-hosted runner: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    
    # add multiple key-value pairs to describe the step
    # multiple steps get multiple dashes
    # when defining steps, etiher script or commands can be executed
    steps:
      - name: Print greeting
        # the run key specifies the command that should be executed in the command line
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      
